model:
  weights: null

  hp:
    add_corr: true
    add_depth: true
    add_lang: true
    add_pixel_loc: true
    add_proprio: true
    attn_dim: 512
    attn_dim_head: 64
    attn_dropout: 0.1
    attn_heads: 8
    depth: 8
    feat_dim: 220 # 72*3 + 4
    im_channels: 64
    point_augment_noise: 0.05
    img_feat_dim: 3
    img_patch_size: 14
    img_size: 224
    lang_dim: 512
    lang_len: 77
    norm_corr: true
    pe_fix: true
    proprio_dim: 3 # 4 # 18
    mvt_cameras: ['top', 'left', 'front']
    stage2_zoom_scale: 4
    stage2_waypoint_label_noise: 0.05
    rotation_aug: #null
      - [-2, -1, 0, -1, -2]
      - [0.1, 0.2, 0.4, 0.2, 0.1]
    use_xformers: true

    gt_hm_sigma: 1.5
    move_pc_in_bound: true
    place_with_mean: false

    amp: True
    bnb: True

    # lr should be thought on per sample basis
    # effective lr is multiplied by bs * num_devices
    lr: 1.25e-5 #1.25e-5 # 1e-4
    warmup_steps: 2000
    optimizer_type: lamb
    lr_cos_dec: true
    add_rgc_loss: true
    transform_augmentation: true
    transform_augmentation_xyz: [0.125, 0.125, 0.125]
    transform_augmentation_rpy: [0.0, 0.0, 45.0]
    lambda_weight_l2: 1e-4 # 1e-6
    num_rotation_classes: 72

    cos_dec_max_step: -1 # will be override during training

    render_with_cpp: true

    resnet: "resnet50"
    vision_encoder: "resnet50"
    
    arp_cfg: 
      n_embd: 128  # or 256, 512
      embd_pdrop: 0.1 
      max_seq_len: 100
      num_layers: 4
      num_latents: 1
      layer_cfg:
        n_head: 8
        mlp_ratio: 4.0
        AdaLN: True
        mlp_dropout: 0.1
        attn_kwargs: { "attn_pdrop": 0.1, "resid_pdrop": 0.1 }
        cond_attn_kwargs: { "attn_pdrop": 0.1, "resid_pdrop": 0.1 }


rolf:
  name: bc
  max_global_step: 50
  warm_up_steps: 0
  train_every: 0
  log_every: 1
  evaluate_every: 1
  ckpt_every: 10
  reward_scale: 1.0
  batch_size: 64
  ob_norm: false
  max_ob_norm_step: 100000000
  clip_obs: .inf
  clip_range: 10
  policy_mlp_dim:
  - 512
  - 256
  - 256
  policy_activation: relu
  tanh_policy: true
  gaussian_policy: false
  actor_lr: 0.0003
  actor_weight_decay: 0
  min_std: 1.0e-10
  max_std: 2
  use_log_std_bias: false
  target_init_std: 0.5
  encoder_type: resnet18
  encoder_image_size:
  - 224
  - 224
  encoder_conv_dim: 32
  encoder_kernel_size:
  - 3
  - 3
  - 3
  - 3
  encoder_stride:
  - 2
  - 1
  - 1
  - 1
  encoder_conv_output_dim: 50
  encoder_soft_update_weight: 0.95
  asym_ac: false
  demo_path: furniture_dataset_processed/low/lamp/
  demo_low_level: false
  demo_subsample_interval: 1
  demo_sample_range:
  - 0.0
  - 1.0
  data_path: null
  num_eval: 50
  bc_lr: 0.0003
  val_split: 0.05
  normalizer: bn
  rnn: false
  rnn_hidden_size: 1024
  rnn_num_layers: 2
  seq_len: 10
  num_demos: null
  encoder: null
  finetune_encoder: false
  device: cuda
  image_agmt: false
  rotation: quaternion
  precision: 32
  is_train: true

env:
  image_size: 224
  cameras: ["front", "wrist"]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6] # [x_min, y_min, z_min, x_max, y_max, z_max] - the metric volume to be voxelized
  time_in_state: false
  voxel_size: 100
  episode_length: 50
  rotation_resolution: 5
  origin_style_state: true


  screen_size: [512, 512]
  action_repeat: 1
  absorbing_state: false
  pixel_ob: false
  state_ob: true
  furniture: null
  record: false
  use_all_cam: false # Use all camera inputs.
  randomness: 'low'
  from_skill: 0
  skill: -1
  high_random_idx: 0
  channel_first: false
  np_step_out: true
  id: FurnitureSim-v0
  concat_robot_state: false

train:
  bs: 96 # 48
  epochs: 100 # 100
  num_gpus: 4
  num_workers: 8 #, need larger value
  num_transitions_per_epoch: 160000
  disp_freq: 100
  cached_dataset_path: null
  save_freq: 10000
  eval_mode: false
  k2k_sample_ratios: 
    place_cups: 1.0
    stack_cups: 1.0
    close_jar: 1.0
    push_buttons: 1.0
    meat_off_grill: 1.0
    stack_blocks: 1.0
    reach_and_drag: 1.0
    slide_block_to_color_target: 1.0
    place_shape_in_shape_sorter: 1.0
    open_drawer: 1.0
    sweep_to_dustpan_of_size: 1.0
    put_groceries_in_cupboard: 1.0
    light_bulb_in: 1.0
    turn_tap: 1.0
    insert_onto_square_peg: 1.0
    put_item_in_drawer: 1.0
    put_money_in_safe: 1.0
    place_wine_at_rack_location: 1.0

eval:
  episode_num: 50
  start_episode: 0
  headless: true
  save_video: false
  device: 0


num_threads: 1
seed: 123
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
init_ckpt_dir: checkpoints/ckpt
gpu: 0
device: cuda
precision: 32
ckpt_num: null
num_eval: 1
record_video: false
record_video_caption: false
record_demo: false

run_prefix: null
notes: null
log_root_dir: log
wandb: false
wandb_entity: 'clvr'
wandb_project: 'furniture-bench'

rank: 0
is_chef: true
num_workers: 1


module_root: /home/by4212/Desktop/hw/rpl/furniture-bench/rolf/rolf/algorithms/rlb
py_module: autoregressive_policy_plus